# Generated by Django 4.2.7 on 2026-03-25 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='leave',
            name='user_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
