# Generated by Django 4.2.7 on 2026-03-30 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_alter_employee_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='department',
            field=models.CharField(blank=True, default='Employee', max_length=100),
        ),
    ]
