# Generated by Django 4.2.7 on 2026-03-25 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0006_candidate_password_employee_password_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='role',
            field=models.CharField(default='employee', max_length=20),
        ),
    ]
